---
title: "comparing_clusters"
author: "Julia Gallucci"
date: "2025-03-03"
output: html_document
---
Load necessary packages
```{r}
library(ggpubr)
library(ggplot2)
library(dplyr)
library(car)
library(knitr)
library(kableExtra)
library(broom)
library(purrr)
library(stringr)
```
Load in data and clean data
```{r}
#load in either Split 1 (Discovery) or Split2 (Replication)
compare_df <- read.csv("/Users/juliagallucci/Desktop/UOFT PhD/ABCD/Split2_RESULTS_5_clust_k44_0.7.csv")

#### Creating piecharts 
compare_df$demo_sex <- factor(compare_df$demo_sex_v2.x, 
                      levels = c(1, 2, 3),
                      labels = c("Male", "Female", "Intersex-Male"))

compare_df$race_ethnicity <- factor(compare_df$race_ethnicity.x,
                                    levels = c(1,2,3,4,5),
                                    labels = c("White","Black","Hispanic","Asian","Other"))

compare_df$groups <- as.factor(compare_df$groups)
compare_df$site_id_l <- as.factor(compare_df$site_id_l.x)

# FOR REPLICATION ONLY: Recode the groups column to match Discovery order
# Use a named character vector to avoid collision
compare_df <- compare_df %>%
  dplyr::mutate(groups = as.character(groups)) %>%
  dplyr::mutate(groups = dplyr::recode(groups,
                         "1" = "temp1",
                         "2" = "temp2",
                         "3" = "temp3",
                         "4" = "temp4",
                         "5" = "temp5")) %>%
  dplyr::mutate(groups = dplyr::recode(groups,
                         "temp1" = "5",
                         "temp2" = "1",
                         "temp3" = "2",
                         "temp4" = "3",
                         "temp5" = "4")) %>%
  dplyr::mutate(groups = as.factor(groups))  # Convert back to factor if needed


clust1 <- compare_df[which(compare_df$groups=="1"),]
clust2 <- compare_df[which(compare_df$groups=="2"),]
clust3 <- compare_df[which(compare_df$groups=="3"),]
clust4 <- compare_df[which(compare_df$groups=="4"),]
clust5 <- compare_df[which(compare_df$groups=="5"),]
```
View demographics across clusters
```{r}
ggplot(compare_df, aes(x = demo_sex, fill = demo_sex)) +
  geom_bar() +
  theme_classic() +
  geom_text(stat = 'count', aes(label = ..count..), 
            position = position_stack(vjust = 0.5), # Center the labels
            color = "white") + # Change text color for visibility
  scale_fill_manual(values = c("Male" = "lightblue", 
                               "Female" = "pink", 
                               "Intersex-Male" = "lightgreen")) + # Custom colors
  theme(text = element_text(size = 14), 
        axis.text = element_text(size = 10)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1), 
        axis.title.x = element_blank()) + 
  ggtitle("Sex By Cluster") +
  facet_wrap(~ groups)

ggplot(compare_df, aes(x=factor(groups), y=interview_age.x, colour=factor(groups), fill=factor(groups))) +
  geom_boxplot(alpha = 0.2) +
  theme_classic() +    theme(text = element_text(size = 12), axis.text = element_text(size = 12)) +
  geom_point(aes(fill = factor(groups), color = factor(groups)), alpha = 0.2,size = 1, colour= "black", shape = 21, position = position_jitterdodge()) +
  ggtitle("Age by Cluster") + 
  xlab("Cluster")+
  ylab("Age in months") 


# Cluster 1
freq_clust1_race <- table(clust1$race_ethnicity)
lbls_clust1_race <- paste(names(freq_clust1_race), "-", round((freq_clust1_race / sum(freq_clust1_race)) * 100, 1), "%", sep = "")
pie(freq_clust1_race, main = "Cluster 1", labels = lbls_clust1_race, cex = 1.5, col = c("lightblue", "lightgreen", "lightpink", "lightyellow", "lightgrey"), lwd = 3)

# Cluster 2
freq_clust2_race <- table(clust2$race_ethnicity)
lbls_clust2_race <- paste(names(freq_clust2_race), "-", round((freq_clust2_race / sum(freq_clust2_race)) * 100, 1), "%", sep = "")
pie(freq_clust2_race, main = "Cluster 2", labels = lbls_clust2_race, cex = 1.5, col = c("lightblue", "lightgreen", "lightpink", "lightyellow", "lightgrey"))

# Cluster 3
freq_clust3_race <- table(clust3$race_ethnicity)
lbls_clust3_race <- paste(names(freq_clust3_race), "-", round((freq_clust3_race / sum(freq_clust3_race)) * 100, 1), "%", sep = "")
pie(freq_clust3_race, main = "Cluster 3", labels = lbls_clust3_race, cex = 1.5, col = c("lightblue", "lightgreen", "lightpink", "lightyellow", "lightgrey"))

# Cluster 4
freq_clust4_race <- table(clust4$race_ethnicity)
lbls_clust4_race <- paste(names(freq_clust4_race), "-", round((freq_clust4_race / sum(freq_clust4_race)) * 100, 1), "%", sep = "")
pie(freq_clust4_race, main = "Cluster 4", labels = lbls_clust4_race, cex = 1.5, col = c("lightblue", "lightgreen", "lightpink", "lightyellow", "lightgrey"))

# Cluster 5
freq_clust5_race <- table(clust5$race_ethnicity)
lbls_clust5_race <- paste(names(freq_clust5_race), "-", round((freq_clust5_race / sum(freq_clust5_race)) * 100, 1), "%", sep = "")
pie(freq_clust5_race, main = "Cluster 5", labels = lbls_clust5_race, cex = 1.5, col = c("lightblue", "lightgreen", "lightpink", "lightyellow", "lightgrey"))

```
View separation of input features across clusters

1. Cognition
```{r fig.height=4, fig.width=3}
cog_stacked <- compare_df %>%
  dplyr::select(groups, 
                nihtbx_flanker_uncorrected, 
                nihtbx_list_uncorrected, 
                nihtbx_cardsort_uncorrected, 
                nihtbx_pattern_uncorrected, 
                nihtbx_picture_uncorrected, 
                nihtbx_reading_uncorrected, 
                nihtbx_picvocab_uncorrected, 
                pea_wiscv_trs, 
                rey_all_correct, 
                lmt_scr_num_correct)

# List of test names
test_names <- c("nihtbx_flanker_uncorrected", 
                "nihtbx_list_uncorrected", 
                "nihtbx_cardsort_uncorrected", 
                "nihtbx_pattern_uncorrected", 
                "nihtbx_picture_uncorrected", 
                "nihtbx_reading_uncorrected", 
                "nihtbx_picvocab_uncorrected", 
                "pea_wiscv_trs", 
                "rey_all_correct", 
                "lmt_scr_num_correct")

cog_long <- cog_stacked %>%
  tidyr::pivot_longer(
    cols = -c(groups),
    names_to = "test",
    values_to = "score"
  )

### effect sizes
# Initialize dataframe to store results
effects <- data.frame(test = character(),
                      Eta2 = numeric(),
                      stringsAsFactors = FALSE)

# Loop through each test
for (test in test_names) {
  model <- lm(as.formula(paste(test, "~ groups")), data = compare_df)
  aov_table <- Anova(model)  # Type II ANOVA from car package
  eta <- eta_squared(aov_table, partial = FALSE)
  
  # Add result (assumes 'groups' is the first row in eta output)
  effects <- rbind(effects, data.frame(test = test,
                                       Eta2 = eta$Eta2[1]))
}
effects <- effects %>% arrange(-Eta2)
print(effects)

# Step 1: Run ANOVA for each measure
aov_results <- cog_long %>%
  group_by(test) %>%
  do(tidy(aov(score ~ groups, data = .))) %>%
  ungroup()

# Step 2: Filter for overall test result only
aov_summary <- aov_results %>%
  filter(term == "groups")

# Step 3: Apply FDR correction
aov_summary <- aov_summary %>%
  mutate(p_adj = p.adjust(p.value, method = "fdr"))

# Step 4: Select significant measures
signif_measures <- aov_summary %>%
  filter(p_adj < 0.05) %>%
  pull(test)

# Step 5: Run Tukey HSD post hoc for significant ones
tukey_results <- cog_long %>%
  filter(test %in% signif_measures) %>%
  group_by(test) %>%
  group_map(~ {
    model <- aov(score ~ groups, data = .x)
    tidy(TukeyHSD(model, "groups"))
  }, .keep = TRUE) %>%
  set_names(signif_measures)

# Optional: Combine results into a data frame
tukey_df <- bind_rows(tukey_results, .id = "test")

tukey_df_filtered <- tukey_df %>% filter(adj.p.value <0.05)

tukey_df_filtered <- tukey_df_filtered %>%
  mutate(direction = case_when(
    estimate > 0 ~ ">",
    estimate < 0 ~ "<",
    TRUE ~ "="  # in case estimate is exactly zero
  ))
tukey_df_filtered <- tukey_df_filtered %>%
  mutate(contrast_direction = paste0(str_replace(contrast, "-", direction))) %>%
  dplyr::select(test, contrast_direction)

aov_summary <- aov_summary %>% arrange(-statistic)
aov_summary <- full_join(aov_summary, effects, by = "test")
aov_summary
tukey_df_filtered
```

2. Environment
```{r fig.height=4, fig.width=3}
env_stacked <- compare_df %>%
  dplyr::select(groups,ADD_nat_perc, income, total_neighbourhood_safety, walkindex, crime, 
                gross_density, no2_pollution, pm_pollution, proximity_to_roads, 
                lead_risk, parental_education, econ_deprivation, sub_availability, 
                total_school_environment, total_parental_support, total_caregiver_support, 
                num_friends, parental_monitoring_total, family_conflict_total, 
                traumatic_events_total, fam_mental_health, family_support, 
                family_obligation, family_independence, family_referent, ethnic_identity, 
                good_events, bad_events, discrim, tbi_ss_worst_overall, maternal_age, 
                paternal_age, birth_weight, premature, illness, breastfeeding, 
                verbal_development, motor_development, pregnancy_complications, 
                birth_complications, maternal_substance_use)

env_long <- env_stacked %>%
  tidyr::pivot_longer(
    cols = -c(groups),
    names_to = "measure",
    values_to = "score"
  )

test_names <- unique(env_long$measure)

### effect sizes
# Initialize dataframe to store results
effects <- data.frame(measure = character(),
                      Eta2 = numeric(),
                      stringsAsFactors = FALSE)

# Loop through each test
for (measure in test_names) {
  model <- lm(as.formula(paste(measure, "~ groups")), data = compare_df)
  aov_table <- Anova(model)  # Type II ANOVA from car package
  eta <- eta_squared(aov_table, partial = FALSE)
  
  # Add result (assumes 'groups' is the first row in eta output)
  effects <- rbind(effects, data.frame(measure = measure,
                                       Eta2 = eta$Eta2[1]))
}
effects <- effects %>% arrange(-Eta2)
print(effects)

# Step 1: Run ANOVA for each measure
aov_results <- env_long %>%
  group_by(measure) %>%
  do(tidy(aov(score ~ groups, data = .))) %>%
  ungroup()

# Step 2: Filter for overall test result only
aov_summary <- aov_results %>%
  filter(term == "groups")

# Step 3: Apply FDR correction
aov_summary <- aov_summary %>%
  mutate(p_adj = p.adjust(p.value, method = "fdr"))

# Step 4: Select significant measures
signif_measures <- aov_summary %>%
  filter(p_adj < 0.05) %>%
  pull(measure)

# Step 5: Run Tukey HSD post hoc for significant ones
tukey_results <- env_long %>%
  filter(measure %in% signif_measures) %>%
  group_by(measure) %>%
  group_map(~ {
    model <- aov(score ~ groups, data = .x)
    tidy(TukeyHSD(model, "groups"))
  }, .keep = TRUE) %>%
  set_names(signif_measures)

# Optional: Combine results into a data frame
tukey_df <- bind_rows(tukey_results, .id = "test")

tukey_df_filtered <- tukey_df %>% filter(adj.p.value <0.05)

tukey_df_filtered <- tukey_df_filtered %>%
  mutate(direction = case_when(
    estimate > 0 ~ ">",
    estimate < 0 ~ "<",
    TRUE ~ "="  # in case estimate is exactly zero
  ))
tukey_df_filtered <- tukey_df_filtered %>%
  mutate(contrast_direction = paste0(str_replace(contrast, "-", direction))) %>%
  dplyr::select(test, contrast_direction)

aov_summary <- aov_summary %>% arrange(-statistic)
aov_summary <- full_join(aov_summary, effects, by = "measure")
aov_summary
tukey_df_filtered
```

3. Volume
```{r}
smri_vol_columns <- grep("smri_vol", names(compare_df), value = TRUE)

vol_stacked <- compare_df %>%
  dplyr::select(groups, smri_vol_columns)

vol_long <- vol_stacked %>%
  tidyr::pivot_longer(
    cols = -c(groups),
    names_to = "brain",
    values_to = "volume"
  )

brain_names <- unique(vol_long$brain)

### effect sizes
# Initialize dataframe to store results
effects <- data.frame(brain = character(),
                      Eta2 = numeric(),
                      stringsAsFactors = FALSE)

# Loop through each test
for (brain in brain_names) {
  model <- lm(as.formula(paste(brain, "~ groups")), data = compare_df)
  aov_table <- Anova(model)  # Type II ANOVA from car package
  eta <- eta_squared(aov_table, partial = FALSE)
  
  # Add result (assumes 'groups' is the first row in eta output)
  effects <- rbind(effects, data.frame(brain = brain,
                                       Eta2 = eta$Eta2[1]))
}
effects <- effects %>% arrange(-Eta2)
print(effects)


# Step 1: Run ANOVA for each measure
aov_results <- vol_long %>%
  group_by(brain) %>%
  do(tidy(aov(volume ~ groups, data = .))) %>%
  ungroup()

# Step 2: Filter for overall brain result only
aov_summary <- aov_results %>%
  filter(term == "groups")

# Step 3: Apply FDR correction
aov_summary <- aov_summary %>%
  mutate(p_adj = p.adjust(p.value, method = "fdr"))

# Step 4: Select significant measures
signif_measures <- aov_summary %>%
  filter(p_adj < 0.05) %>%
  pull(brain)

# Step 5: Run Tukey HSD post hoc for significant ones
tukey_results <- vol_long %>%
  filter(brain %in% signif_measures) %>%
  group_by(brain) %>%
  group_map(~ {
    model <- aov(volume ~ groups, data = .x)
    tidy(TukeyHSD(model, "groups"))
  }, .keep = TRUE) %>%
  set_names(signif_measures)

# Optional: Combine results into a data frame
tukey_df <- bind_rows(tukey_results, .id = "brain")

tukey_df_filtered <- tukey_df %>% filter(adj.p.value <0.05)

tukey_df_filtered <- tukey_df_filtered %>%
  mutate(direction = case_when(
    estimate > 0 ~ ">",
    estimate < 0 ~ "<",
    TRUE ~ "="  # in case estimate is exactly zero
  ))
tukey_df_filtered <- tukey_df_filtered %>%
  mutate(contrast_direction = paste0(str_replace(contrast, "-", direction))) %>%
  dplyr::select(brain, contrast_direction)

tukey_df_filtered <- tukey_df_filtered %>%
  mutate(brain = str_remove(brain, "smri_vol_scs_"),                  # Remove the prefix
         brain = str_replace(brain, "(.*)(lh|rh)$", "\\2_\\1"))

aov_summary <- full_join(aov_summary, effects, by = "brain")

aov_summary <- aov_summary %>%
  mutate(brain = str_remove(brain, "smri_vol_scs_"),                  # Remove the prefix
         brain = str_replace(brain, "(.*)(lh|rh)$", "\\2_\\1"))
# Define replacements as named vector
vol_replacements <- c(
  "bstem" = "Brain Stem",
  "rh_ltventricle" = "Right Lateral Ventricle",
  "lh_ltventricle" = "Left Lateral Ventricle",
  "lh_pallidum" = "Left Pallidum",
  "rh_pallidum" = "Right Pallidum",
  "rh_tp" = "Right Thalamus Proper",
  "lh_tp" = "Left Thalamus Proper",
  "lh_putamen" = "Left Putamen",
  "rh_putamen" = "Right Putamen",
  "rh_vedc" = "Right VentralDC",
  "lh_vedc" = "Left VentralDC",
  "rh_caudate" = "Right Caudate",
  "lh_caudate" = "Left Caudate",
  "rh_hpus" = "Right Hippocampus",
  "lh_hpus" = "Left Hippocampus",
  "rh_crbcortex" = "Right Cerebellum Cortex",
  "lh_crbcortex" = "Left Cerebellum Cortex",
  "rh_crbwmatter" = "Right Cerebellum White Matter",
  "lh_amygdala" = "Left Amygdala",
  "rh_amygdala" = "Right Amygdala",
  "aal" = "Left Accumbens Area",
  "aar" = "Right Accumbens Area",
  "rh_inflatvent" = "Right Inferior Lateral Ventricle",
  "lh_inflatvent" = "Left Inferior Lateral Ventricle",
  "x3rd-ventricle" = "Ventricle 3rd",
  "x4th-ventricle" = "Ventricle 4th"
)
# Function to replace all keys in a vector based on the vol_replacements
replace_vol_labels <- function(vec, replacements) {
  for (abbr in names(replacements)) {
    vec <- gsub(abbr, replacements[[abbr]], vec)
  }
  return(vec)
}

aov_summary$brain <- replace_vol_labels(aov_summary$brain, vol_replacements)
# Apply the replacement function to the 'brain' column 
tukey_df_filtered$brain <- replace_vol_labels(tukey_df_filtered$brain, vol_replacements)
aov_summary <- aov_summary %>% arrange(-statistic)
aov_summary
tukey_df_filtered
```
4. Thickness
```{r}
smri_thick_columns <- grep("smri_thick_cdk_", names(compare_df), value = TRUE)

thick_stacked <- compare_df %>%
  dplyr::select(groups,smri_thick_columns)

thick_long <- thick_stacked %>%
  tidyr::pivot_longer(
    cols = -c(groups),
    names_to = "brain",
    values_to = "thick"
  )

brain_names <- unique(thick_long$brain)

### effect sizes
# Initialize dataframe to store results
effects <- data.frame(brain = character(),
                      Eta2 = numeric(),
                      stringsAsFactors = FALSE)

# Loop through each test
for (brain in brain_names) {
  model <- lm(as.formula(paste(brain, "~ groups")), data = compare_df)
  aov_table <- Anova(model)  # Type II ANOVA from car package
  eta <- eta_squared(aov_table, partial = FALSE)
  
  # Add result (assumes 'groups' is the first row in eta output)
  effects <- rbind(effects, data.frame(brain = brain,
                                       Eta2 = eta$Eta2[1]))
}
effects <- effects %>% arrange(-Eta2)
print(effects)

# Step 1: Run ANOVA for each measure
aov_results <- thick_long %>%
  group_by(brain) %>%
  do(tidy(aov(thick ~ groups, data = .))) %>%
  ungroup()

# Step 2: Filter for overall brain result only
aov_summary <- aov_results %>%
  filter(term == "groups")

# Step 3: Apply FDR correction
aov_summary <- aov_summary %>%
  mutate(p_adj = p.adjust(p.value, method = "fdr"))

# Step 4: Select significant measures
signif_measures <- aov_summary %>%
  filter(p_adj < 0.05) %>%
  pull(brain)

# Step 5: Run Tukey HSD post hoc for significant ones
tukey_results <- thick_long %>%
  filter(brain %in% signif_measures) %>%
  group_by(brain) %>%
  group_map(~ {
    model <- aov(thick ~ groups, data = .x)
    tidy(TukeyHSD(model, "groups"))
  }, .keep = TRUE) %>%
  set_names(signif_measures)

# Optional: Combine results into a data frame
tukey_df <- bind_rows(tukey_results, .id = "brain")

tukey_df_filtered <- tukey_df %>% filter(adj.p.value <0.05)

tukey_df_filtered <- tukey_df_filtered %>%
  mutate(direction = case_when(
    estimate > 0 ~ ">",
    estimate < 0 ~ "<",
    TRUE ~ "="  # in case estimate is exactly zero
  ))
tukey_df_filtered <- tukey_df_filtered %>%
  mutate(contrast_direction = paste0(str_replace(contrast, "-", direction))) %>%
  dplyr::select(brain, contrast_direction)

tukey_df_filtered <- tukey_df_filtered %>%
  mutate(brain = str_remove(brain, "smri_thick_cdk_"),                  # Remove the prefix
         brain = str_replace(brain, "(.*)(lh|rh)$", "\\2_\\1"))

aov_summary <- full_join(aov_summary, effects, by = "brain")

aov_summary <- aov_summary %>%
  mutate(brain = str_remove(brain, "smri_thick_cdk_"),                  # Remove the prefix
         brain = str_replace(brain, "(.*)(lh|rh)$", "\\2_\\1"))

# Vector of patterns and replacements
patterns <- c("lh_rracate", "rh_rracate", "lh_precn", "rh_precn", "lh_postcn", "rh_postcn",
              "lh_locc", "rh_locc", "rh_paracn", "lh_paracn", "rh_mdtm", "lh_mdtm",
              "lh_pericc", "rh_pericc", "rh_iftm", "lh_iftm", "lh_supl", "rh_supl",
              "rh_sufr", "rh_sm", "lh_sm", "lh_ifpl", "rh_ifpl", "rh_parahpal",
              "lh_pc", "rh_pc", "rh_sutm", "lh_sutm", "lh_cdmdfr", "rh_cdmdfr",
              "lh_parahpal", "rh_parahpal", "lh_tmpole", "rh_tmpole", "rh_trvtm", "lh_trvtm",
              "rh_frpole", "lh_frpole", "lh_ehinal", "lh_ptcate", "rh_ihcate", "rh_lobfr",
              "lh_lobfr", "lh_ihcate", "lh_mobfr", "rh_mobfr", "lh_sufr", "lh_parsopc",
              "rh_parsopc", "lh_rrmdfr", "rh_rrmdfr", "rh_parstgris", "lh_parstgris",
              "rh_parsobis", "lh_parsobis", "rh_ptcate", "rh_cdacate", "lh_cdacate", "rh_ehinal",
              "lh_bankssts","lh_cuneus","lh_fusiform","lh_insula","lh_lingual",
              "rh_bankssts","rh_cuneus","rh_fusiform","rh_insula","rh_lingual")
replacements <- c("Left Rostral Anterior Cingulate", "Right Rostral Anterior Cingulate", "Left precentral", "Right precentral",
                  "Left Post-central", "Right Post-central", "Left Lateral Occipital", "Right Lateral Occipital", "Right Paracentral",
                  "Left Paracentral", "Right Middle Temporal", "Left Middle Temporal", "Left Pericalcarine", "Right Pericalcarine",
                  "Right Inferior Temporal", "Left Inferior Temporal", "Left Superior Parietal", "Right Superior Parietal",
                  "Right Superior Frontal", "Right Supramarginal", "Left Supramarginal", "Left Inferior Parietal",
                  "Right Inferior Parietal", "Right Parahippocampal", "Left Precuneus", "Right precuneus", "Right Superior Temporal",
                  "Left Superior Temporal", "Left Caudal Middle Frontal", "Right Caudal Middle Frontal", "Left Parahippocampal",
                  "Right Parahippocampal", "Left Temporal Pole", "Right Temporal Pole", "Right Transverse Temporal",
                  "Left Transverse Temporal", "Right Frontal Pole", "Left Frontal Pole", "Left Entorhinal", "Left Posterior Cingulate",
                  "Right Isthmus Cingulate", "Right Lateral Orbitofrontal", "Left Lateral Orbitofrontal", "Left Isthmus Cingulate",
                  "Left Medial Orbitofrontal", "Right Medial Orbitofrontal", "Left Superior Frontal", "Left Parsopercularis",
                  "Right Parsopercularis", "Left Rostral Middle Frontal", "Right Rostral Middle Frontal", "Right Parstriangularis",
                  "Left Parstriangularis", "Right Parsorbitalis", "Left Parsorbitalis", "Right Posterior Cingulate",
                  "Right Caudal Anterior Cingulate", "Left Caudal Anterior Cingulate", "Right Entorhinal",
                  "Left Bankssts","Left Cuneus","Left Fusiform","Left Insula","Left Lingual",
                  "Right Bankssts","Right Cuneus","Right Fusiform","Right Insula","Right Lingual")

# Function to replace labels in the 'brain' column
replace_labels <- function(df, patterns, replacements) {
  for(i in seq_along(patterns)) {
    df$brain <- gsub(patterns[i], replacements[i], df$brain)
  }
  return(df)
}

# Apply the replacement function to the 'brain' column in All_results
tukey_df_filtered <- replace_labels(tukey_df_filtered,patterns, replacements)
aov_summary <- replace_labels(aov_summary,patterns,replacements)
aov_summary <- aov_summary %>% arrange(-statistic)

aov_summary
tukey_df_filtered
```

5. Area
```{r}
smri_area_columns <- grep("smri_area_cdk_", names(compare_df), value = TRUE)

area_stacked <- compare_df %>%
  dplyr::select(groups,smri_area_columns)

area_long <- area_stacked %>%
  tidyr::pivot_longer(
    cols = -c(groups),
    names_to = "brain",
    values_to = "area"
  )

brain_names <- unique(area_long$brain)

### effect sizes
# Initialize dataframe to store results
effects <- data.frame(brain = character(),
                      Eta2 = numeric(),
                      stringsAsFactors = FALSE)

# Loop through each test
for (brain in brain_names) {
  model <- lm(as.formula(paste(brain, "~ groups")), data = compare_df)
  aov_table <- Anova(model)  # Type II ANOVA from car package
  eta <- eta_squared(aov_table, partial = FALSE)
  
  # Add result (assumes 'groups' is the first row in eta output)
  effects <- rbind(effects, data.frame(brain = brain,
                                       Eta2 = eta$Eta2[1]))
}
effects <- effects %>% arrange(-Eta2)
print(effects)

# Step 1: Run ANOVA for each measure
aov_results <- area_long %>%
  group_by(brain) %>%
  do(tidy(aov(area ~ groups, data = .))) %>%
  ungroup()

# Step 2: Filter for overall brain result only
aov_summary <- aov_results %>%
  filter(term == "groups")

# Step 3: Apply FDR correction
aov_summary <- aov_summary %>%
  mutate(p_adj = p.adjust(p.value, method = "fdr"))

# Step 4: Select significant measures
signif_measures <- aov_summary %>%
  filter(p_adj < 0.05) %>%
  pull(brain)

# Step 5: Run Tukey HSD post hoc for significant ones
tukey_results <- area_long %>%
  filter(brain %in% signif_measures) %>%
  group_by(brain) %>%
  group_map(~ {
    model <- aov(area ~ groups, data = .x)
    tidy(TukeyHSD(model, "groups"))
  }, .keep = TRUE) %>%
  set_names(signif_measures)

# Optional: Combine results into a data frame
tukey_df <- bind_rows(tukey_results, .id = "brain")

tukey_df_filtered <- tukey_df %>% filter(adj.p.value <0.05)

tukey_df_filtered <- tukey_df_filtered %>%
  mutate(direction = case_when(
    estimate > 0 ~ ">",
    estimate < 0 ~ "<",
    TRUE ~ "="  # in case estimate is exactly zero
  ))
tukey_df_filtered <- tukey_df_filtered %>%
  mutate(contrast_direction = paste0(str_replace(contrast, "-", direction))) %>%
  dplyr::select(brain, contrast_direction)

tukey_df_filtered <- tukey_df_filtered %>%
  mutate(brain = str_remove(brain, "smri_area_cdk_"),                  # Remove the prefix
         brain = str_replace(brain, "(.*)(lh|rh)$", "\\2_\\1"))

aov_summary <- full_join(aov_summary, effects, by = "brain")

aov_summary <- aov_summary %>%
  mutate(brain = str_remove(brain, "smri_area_cdk_"),                  # Remove the prefix
         brain = str_replace(brain, "(.*)(lh|rh)$", "\\2_\\1"))

# Apply the replacement function to the 'brain' column in All_results
tukey_df_filtered <- replace_labels(tukey_df_filtered,patterns, replacements)
aov_summary <- replace_labels(aov_summary,patterns,replacements)
aov_summary <- aov_summary %>% arrange(-statistic)

aov_summary
tukey_df_filtered
```

6.Resting state
```{r}
rsfmri_columns <- grep("rsfmri", names(compare_df), value = TRUE)

RS_stacked <- compare_df %>%
  dplyr::select(groups, 
                race_ethnicity,
                demo_sex,
                interview_age.x,
                site_id_l,rsfmri_columns)

RS_long <- RS_stacked %>%
  tidyr::pivot_longer(
    cols = -c(groups, race_ethnicity, demo_sex, interview_age.x, site_id_l),
    names_to = "brain",
    values_to = "RS"
  )

brain_names <- unique(RS_long$brain)

### effect sizes
# Initialize dataframe to store results
effects <- data.frame(brain = character(),
                      Eta2 = numeric(),
                      stringsAsFactors = FALSE)

# Loop through each test
for (brain in brain_names) {
  model <- lm(as.formula(paste(brain, "~ groups")), data = compare_df)
  aov_table <- Anova(model)  # Type II ANOVA from car package
  eta <- eta_squared(aov_table, partial = FALSE)
  
  # Add result (assumes 'groups' is the first row in eta output)
  effects <- rbind(effects, data.frame(brain = brain,
                                       Eta2 = eta$Eta2[1]))
}
effects <- effects %>% arrange(-Eta2)
print(effects)

# Step 1: Run ANOVA for each measure
aov_results <- RS_long %>%
  group_by(brain) %>%
  do(tidy(aov(RS ~ groups, data = .))) %>%
  ungroup()

# Step 2: Filter for overall brain result only
aov_summary <- aov_results %>%
  filter(term == "groups")

# Step 3: Apply FDR correction
aov_summary <- aov_summary %>%
  mutate(p_adj = p.adjust(p.value, method = "fdr"))

# Step 4: Select significant measures
signif_measures <- aov_summary %>%
  filter(p_adj < 0.05) %>%
  pull(brain)

# Step 5: Run Tukey HSD post hoc for significant ones
tukey_results <- RS_long %>%
  filter(brain %in% signif_measures) %>%
  group_by(brain) %>%
  group_map(~ {
    model <- aov(RS ~ groups, data = .x)
    tidy(TukeyHSD(model, "groups"))
  }, .keep = TRUE) %>%
  set_names(signif_measures)

# Optional: Combine results into a data frame
tukey_df <- bind_rows(tukey_results, .id = "brain")

tukey_df_filtered <- tukey_df %>% filter(adj.p.value <0.05)

tukey_df_filtered <- tukey_df_filtered %>%
  mutate(direction = case_when(
    estimate > 0 ~ ">",
    estimate < 0 ~ "<",
    TRUE ~ "="  # in case estimate is exactly zero
  ))
tukey_df_filtered <- tukey_df_filtered %>%
  mutate(contrast_direction = paste0(str_replace(contrast, "-", direction))) %>%
  dplyr::select(brain, contrast_direction)


aov_summary <- full_join(aov_summary, effects, by = "brain")

# Define cortical network (ngd) mappings
ngd_mapping <- list(
  dla = "Dorsal Attention",
  cerc = "Cingulo-Opercular",
  smh = "Sensorimotor-Hand",
  smm = "Sensorimotor-Mouth",
  vta = "Ventral Attention",
  cgc = "Cingulo-opercular",
  rst = "Retrosplenial Temporal",
  df = "Default",
  sa = "Salience",
  au = "Auditory",
  vs = "Visual",
  fopa = "Fronto-Parietal",
  dsa = "Dorsal Attention",
  copa = "Cingulo-Parietal",
  none = "Unassigned",
  ad = "Auditory",
  ca = "Cingulo-Parietal",
  dt = "Default Mode",
  fo = "Fronto-Parietal",
  n = "Non-specific",
  rspltp = "Retrosplenial Temporal"
)
# Define subcortical structure (scs) mappings
scs_mapping <- list(
  bs = "Brainstem",
  aglh = "Left amygdala",
  pllh = "Left pallidum",
  hplh = "Left hippocampus",
  cderh = "Right caudate",
  hprh = "Right hippocampus",
  aarh = "Right accumbens",
  ptrh = "Right putamen",
  crcxlh = "Left cerebellar cortex",
  plrh = "Right pallidum",
  ptlh = "Left putamen",
  aalh = "Left accumbens",
  thplh = "Left thalamus",
  thprh = "Right thalamus",
  vtdcrh = "Right ventral DC",
  vtdclh = "Left ventral DC",
  agrh = "Right amygdala",
  cdelh = "Left caudate",
  crcxrh = "Right cerebellar cortex"
)
rename_feature <- function(feature) {
  parts <- strsplit(feature, "_")[[1]]
  if (parts[2] == "cor" || parts[2] == "c") {
    source_network <- parts[4]
    target_network <- parts[6]
    if (parts[5] == "scs") {
      source_name <- ngd_mapping[[source_network]]
      target_name <- scs_mapping[[target_network]]
      renamed <- paste(source_name, "to", target_name)
    } else if (parts[5] == "ngd") {
      source_name <- ngd_mapping[[source_network]]
      target_name <- ngd_mapping[[target_network]]
      renamed <- paste(source_name, "to", target_name)
    } else {
      renamed <- feature
    }
  } else {
    renamed <- feature
  }
  return(renamed)
}
# Create a new column with renamed features
tukey_df_filtered$brain <- sapply(tukey_df_filtered$brain, rename_feature)
aov_summary$brain <- sapply(aov_summary$brain, rename_feature)
aov_summary <- aov_summary %>% arrange(-statistic)

aov_summary
tukey_df_filtered

```
