---
title: "Effect Size Plotting"
author: "Julia Gallucci"
date: "05/05/2025"
output: html_document
---
Load necessary packages
```{r}
library(ggsegSchaefer)
library(ggsegDesterieux)
library(ggseg)
library(ggplot2)
library(tidyr)
library(dplyr)
library(stringr)
library(reshape2)
library(tidygraph)
library(ggraph)
```

Cortical Thickness
```{r}
#Modify input accordingly
ct_effectsize <- read.csv("../split2_C1_CT_effectsize.csv")
ct_effectsize_cluster <- ct_effectsize %>%
  mutate(label = str_remove(label, "smri_thick_cdk_"),               
         label = str_replace(label, "(.*)(lh|rh)$", "\\2_\\1")) 

# Replace labels with correct ones per atlas
ct_effectsize_cluster$label <- gsub("lh_rracate", "lh_rostralanteriorcingulate", ct_effectsize_cluster$label)
ct_effectsize_cluster$label <- gsub("rh_rracate", "rh_rostralanteriorcingulate", ct_effectsize_cluster$label)
ct_effectsize_cluster$label <- gsub("lh_precn", "lh_precentral", ct_effectsize_cluster$label)
ct_effectsize_cluster$label <- gsub("rh_precn", "rh_precentral", ct_effectsize_cluster$label)
ct_effectsize_cluster$label <- gsub("lh_postcn", "lh_postcentral", ct_effectsize_cluster$label)
ct_effectsize_cluster$label <- gsub("rh_postcn", "rh_postcentral", ct_effectsize_cluster$label)
ct_effectsize_cluster$label <- gsub("lh_locc", "lh_lateraloccipital", ct_effectsize_cluster$label)
ct_effectsize_cluster$label <- gsub("rh_locc", "rh_lateraloccipital", ct_effectsize_cluster$label)
ct_effectsize_cluster$label <- gsub("rh_paracn", "rh_paracentral", ct_effectsize_cluster$label)
ct_effectsize_cluster$label <- gsub("lh_paracn", "lh_paracentral", ct_effectsize_cluster$label)
ct_effectsize_cluster$label <- gsub("rh_mdtm", "rh_middletemporal", ct_effectsize_cluster$label)
ct_effectsize_cluster$label <- gsub("lh_mdtm", "lh_middletemporal", ct_effectsize_cluster$label)
ct_effectsize_cluster$label <- gsub("lh_pericc", "lh_pericalcarine", ct_effectsize_cluster$label)
ct_effectsize_cluster$label <- gsub("rh_pericc", "rh_pericalcarine", ct_effectsize_cluster$label)
ct_effectsize_cluster$label <- gsub("rh_iftm", "rh_inferiortemporal", ct_effectsize_cluster$label)
ct_effectsize_cluster$label <- gsub("lh_iftm", "lh_inferiortemporal", ct_effectsize_cluster$label)
ct_effectsize_cluster$label <- gsub("lh_supl", "lh_superiorparietal", ct_effectsize_cluster$label)
ct_effectsize_cluster$label <- gsub("rh_supl", "rh_superiorparietal", ct_effectsize_cluster$label)
ct_effectsize_cluster$label <- gsub("rh_sufr", "rh_superiorfrontal", ct_effectsize_cluster$label)
ct_effectsize_cluster$label <- gsub("rh_sm", "rh_supramarginal", ct_effectsize_cluster$label)
ct_effectsize_cluster$label <- gsub("lh_sm", "lh_supramarginal", ct_effectsize_cluster$label)
ct_effectsize_cluster$label <- gsub("lh_ifpl", "lh_inferiorparietal", ct_effectsize_cluster$label)
ct_effectsize_cluster$label <- gsub("rh_ifpl", "rh_inferiorparietal", ct_effectsize_cluster$label)
ct_effectsize_cluster$label <- gsub("rh_parahpal", "rh_parahippocampal", ct_effectsize_cluster$label)
ct_effectsize_cluster$label <- gsub("lh_pc", "lh_precuneus", ct_effectsize_cluster$label)
ct_effectsize_cluster$label <- gsub("rh_pc", "rh_precuneus", ct_effectsize_cluster$label)
ct_effectsize_cluster$label <- gsub("rh_sutm", "rh_superiortemporal", ct_effectsize_cluster$label)
ct_effectsize_cluster$label <- gsub("lh_sutm", "lh_superiortemporal", ct_effectsize_cluster$label)
ct_effectsize_cluster$label <- gsub("lh_cdmdfr", "lh_caudalmiddlefrontal", ct_effectsize_cluster$label)
ct_effectsize_cluster$label <- gsub("rh_cdmdfr", "rh_caudalmiddlefrontal", ct_effectsize_cluster$label)
ct_effectsize_cluster$label <- gsub("lh_parahpal", "lh_parahippocampal", ct_effectsize_cluster$label)
ct_effectsize_cluster$label <- gsub("rh_parahpal", "rh_parahippocampal", ct_effectsize_cluster$label)
ct_effectsize_cluster$label <- gsub("lh_tmpole", "lh_temporalpole", ct_effectsize_cluster$label)
ct_effectsize_cluster$label <- gsub("rh_tmpole", "rh_temporalpole", ct_effectsize_cluster$label)
ct_effectsize_cluster$label <- gsub("rh_trvtm", "rh_transversetemporal", ct_effectsize_cluster$label)
ct_effectsize_cluster$label <- gsub("lh_trvtm", "lh_transversetemporal", ct_effectsize_cluster$label)
ct_effectsize_cluster$label <- gsub("rh_frpole", "rh_frontalpole", ct_effectsize_cluster$label)
ct_effectsize_cluster$label <- gsub("lh_frpole", "lh_frontalpole", ct_effectsize_cluster$label)
ct_effectsize_cluster$label <- gsub("lh_ehinal", "lh_entorhinal", ct_effectsize_cluster$label)
ct_effectsize_cluster$label <- gsub("lh_ptcate", "lh_posteriorcingulate", ct_effectsize_cluster$label)
ct_effectsize_cluster$label <- gsub("rh_ihcate", "rh_isthmuscingulate", ct_effectsize_cluster$label)
ct_effectsize_cluster$label <- gsub("rh_lobfr", "rh_lateralorbitofrontal", ct_effectsize_cluster$label)
ct_effectsize_cluster$label <- gsub("lh_lobfr", "lh_lateralorbitofrontal", ct_effectsize_cluster$label)
ct_effectsize_cluster$label <- gsub("lh_sutm", "lh_superiortemporal", ct_effectsize_cluster$label)
ct_effectsize_cluster$label <- gsub("rh_sutm", "rh_superiortemporal", ct_effectsize_cluster$label)
ct_effectsize_cluster$label <- gsub("lh_ihcate", "lh_isthmuscingulate", ct_effectsize_cluster$label)
ct_effectsize_cluster$label <- gsub("lh_mobfr", "lh_medialorbitofrontal", ct_effectsize_cluster$label)
ct_effectsize_cluster$label <- gsub("rh_mobfr", "rh_medialorbitofrontal", ct_effectsize_cluster$label)
ct_effectsize_cluster$label <- gsub("lh_sufr", "lh_superiorfrontal", ct_effectsize_cluster$label)
ct_effectsize_cluster$label <- gsub("lh_parsopc", "lh_parsopercularis", ct_effectsize_cluster$label)
ct_effectsize_cluster$label <- gsub("rh_parsopc", "rh_parsopercularis", ct_effectsize_cluster$label)
ct_effectsize_cluster$label <- gsub("lh_cdmdfr", "lh_caudalmiddlefrontal", ct_effectsize_cluster$label)
ct_effectsize_cluster$label <- gsub("lh_rrmdfr", "lh_rostralmiddlefrontal", ct_effectsize_cluster$label)
ct_effectsize_cluster$label <- gsub("rh_rrmdfr", "rh_rostralmiddlefrontal", ct_effectsize_cluster$label)
ct_effectsize_cluster$label <- gsub("rh_sm", "rh_supramarginal", ct_effectsize_cluster$label)
ct_effectsize_cluster$label <- gsub("rh_parstgris", "rh_parstriangularis", ct_effectsize_cluster$label)
ct_effectsize_cluster$label <- gsub("lh_parstgris", "lh_parstriangularis", ct_effectsize_cluster$label)
ct_effectsize_cluster$label <- gsub("rh_parsobis", "rh_parsorbitalis", ct_effectsize_cluster$label)
ct_effectsize_cluster$label <- gsub("lh_parsobis", "lh_parsorbitalis", ct_effectsize_cluster$label)
ct_effectsize_cluster$label <- gsub("rh_ptcate", "rh_posteriorcingulate", ct_effectsize_cluster$label)
ct_effectsize_cluster$label <- gsub("rh_cdacate", "rh_caudalanteriorcingulate", ct_effectsize_cluster$label)
ct_effectsize_cluster$label <- gsub("lh_cdacate", "lh_caudalanteriorcingulate", ct_effectsize_cluster$label)
ct_effectsize_cluster$label <- gsub("rh_ehinal", "rh_entorhinal", ct_effectsize_cluster$label)

#plot
ggseg( 
      .data = ct_effectsize_cluster, 
      colour = "black",
      mapping = aes(fill = tstat), 
      position = "stacked") +
  theme_void() +
  scale_fill_gradient2(low = "blue", mid = "white", high = "red", midpoint = 0,lim = c(-15,15))+
  labs(title = "Cortical Thickness NonPLE - Cluster 1", fill = "T-stat")
```

Sub-cortical Volume
```{r}
#Modify input accordingly
vol_effectsize <- read.csv("..//split2_C1_VOL_effectsize.csv")
vol_effectsize_cluster <- vol_effectsize %>%
  mutate(label = str_remove(label, "smri_vol_scs_"),                
         label = str_replace(label, "(.*)(lh|rh)$", "\\2_\\1")) 

# Replace incorrect labels with correct ones
vol_effectsize_cluster$label <- gsub("bstem", "Brain-Stem", vol_effectsize_cluster$label)
vol_effectsize_cluster$label <- gsub("rh_ltventricle", "Right-Lateral-Ventricle", vol_effectsize_cluster$label)
vol_effectsize_cluster$label <- gsub("lh_ltventricle", "Left-Lateral-Ventricle", vol_effectsize_cluster$label)
vol_effectsize_cluster$label <- gsub("lh_pallidum", "Left-Pallidum", vol_effectsize_cluster$label)
vol_effectsize_cluster$label <- gsub("rh_pallidum", "Right-Pallidum", vol_effectsize_cluster$label)
vol_effectsize_cluster$label <- gsub("rh_tp", "Right-Thalamus-Proper", vol_effectsize_cluster$label)
vol_effectsize_cluster$label <- gsub("lh_tp", "Left-Thalamus-Proper", vol_effectsize_cluster$label)
vol_effectsize_cluster$label <- gsub("lh_putamen", "Left-Putamen", vol_effectsize_cluster$label)
vol_effectsize_cluster$label <- gsub("rh_putamen", "Right-Putamen", vol_effectsize_cluster$label)
vol_effectsize_cluster$label <- gsub("rh_vedc", "Right-VentralDC", vol_effectsize_cluster$label)
vol_effectsize_cluster$label <- gsub("lh_vedc", "Left-VentralDC", vol_effectsize_cluster$label)
vol_effectsize_cluster$label <- gsub("rh_caudate", "Right-Caudate", vol_effectsize_cluster$label)
vol_effectsize_cluster$label <- gsub("lh_caudate", "Left-Caudate", vol_effectsize_cluster$label)
vol_effectsize_cluster$label <- gsub("rh_hpus", "Right-Hippocampus", vol_effectsize_cluster$label)
vol_effectsize_cluster$label <- gsub("lh_hpus", "Left-Hippocampus", vol_effectsize_cluster$label)
vol_effectsize_cluster$label <- gsub("rh_crbcortex", "Right-Cerebellum-Cortex", vol_effectsize_cluster$label)
vol_effectsize_cluster$label <- gsub("lh_crbcortex", "Left-Cerebellum-Cortex", vol_effectsize_cluster$label)
vol_effectsize_cluster$label <- gsub("4thventricle", "x4th-ventricle", vol_effectsize_cluster$label)
vol_effectsize_cluster$label <- gsub("3rdventricle", "x3rd-ventricle", vol_effectsize_cluster$label)
vol_effectsize_cluster$label <- gsub("rh_crbwmatter", "Right-Cerebellum-White-Matter", vol_effectsize_cluster$label)
vol_effectsize_cluster$label <- gsub("lh_amygdala", "Left-Amygdala", vol_effectsize_cluster$label)
vol_effectsize_cluster$label <- gsub("rh_amygdala", "Right-Amygdala", vol_effectsize_cluster$label)

ggseg( atlas = ggseg::aseg,
      .data = vol_effectsize_cluster, 
      colour = "black",
      mapping = aes(fill = tstat), 
      position = "stacked") +
  theme_void() +
  scale_fill_gradient2(low = "blue", mid = "white", high = "red", midpoint = 0,lim = c(-15,15))+
  labs(title = "Subcortical Volume NonPLE- Cluster1", fill = "T-stat")
```

Surface Area
```{r}
#Modify input accordingly
sa_effectsize <- read.csv("../split2_C1_SA_effectsize.csv")

sa_effectsize_cluster <- sa_effectsize %>%
  mutate(label = str_remove(label, "smri_area_cdk_"),
         label = str_replace(label, "(.*)(lh|rh)$", "\\2_\\1")) 

# Replace labels with correct ones per atlas
sa_effectsize_cluster$label <- gsub("rh_rracate", "rh_rostralanteriorcingulate", sa_effectsize_cluster$label)
sa_effectsize_cluster$label <- gsub("lh_rracate", "lh_rostralanteriorcingulate", sa_effectsize_cluster$label)
sa_effectsize_cluster$label <- gsub("rh_pericc", "rh_pericalcarine", sa_effectsize_cluster$label)
sa_effectsize_cluster$label <- gsub("lh_pericc", "lh_pericalcarine", sa_effectsize_cluster$label)
sa_effectsize_cluster$label <- gsub("rh_parstgris", "rh_parstriangularis", sa_effectsize_cluster$label)
sa_effectsize_cluster$label <- gsub("rh_cdmdfr", "rh_caudalmiddlefrontal", sa_effectsize_cluster$label)
sa_effectsize_cluster$label <- gsub("lh_iftm", "lh_inferiortemporal", sa_effectsize_cluster$label)
sa_effectsize_cluster$label <- gsub("rh_iftm", "rh_inferiortemporal", sa_effectsize_cluster$label)
sa_effectsize_cluster$label <- gsub("rh_tmpole", "rh_temporalpole", sa_effectsize_cluster$label)
sa_effectsize_cluster$label <- gsub("lh_tmpole", "lh_temporalpole", sa_effectsize_cluster$label)
sa_effectsize_cluster$label <- gsub("lh_cdacate", "lh_caudalanteriorcingulate", sa_effectsize_cluster$label)
sa_effectsize_cluster$label <- gsub("lh_ptcate", "lh_posteriorcingulate", sa_effectsize_cluster$label)
sa_effectsize_cluster$label <- gsub("rh_ptcate", "rh_posteriorcingulate", sa_effectsize_cluster$label)
sa_effectsize_cluster$label <- gsub("lh_ehinal", "lh_entorhinal", sa_effectsize_cluster$label)
sa_effectsize_cluster$label <- gsub("rh_ehinal", "rh_entorhinal", sa_effectsize_cluster$label)
sa_effectsize_cluster$label <- gsub("rh_trvtm", "rh_transversetemporal", sa_effectsize_cluster$label)
sa_effectsize_cluster$label <- gsub("lh_trvtm", "lh_transversetemporal", sa_effectsize_cluster$label)
sa_effectsize_cluster$label <- gsub("rh_ifpl", "rh_inferiorparietal", sa_effectsize_cluster$label)
sa_effectsize_cluster$label <- gsub("lh_ifpl", "lh_inferiorparietal", sa_effectsize_cluster$label)
sa_effectsize_cluster$label <- gsub("rh_parahpal", "rh_parahippocampal", sa_effectsize_cluster$label)
sa_effectsize_cluster$label <- gsub("rh_mdtm", "rh_middletemporal", sa_effectsize_cluster$label)
sa_effectsize_cluster$label <- gsub("lh_mdtm", "lh_middletemporal", sa_effectsize_cluster$label)
sa_effectsize_cluster$label <- gsub("lh_sm", "lh_supramarginal", sa_effectsize_cluster$label)
sa_effectsize_cluster$label <- gsub("rh_sm", "rh_supramarginal", sa_effectsize_cluster$label)
sa_effectsize_cluster$label <- gsub("lh_parahpal", "lh_parahippocampal", sa_effectsize_cluster$label)
sa_effectsize_cluster$label <- gsub("lh_cdmdfr", "lh_caudalmiddlefrontal", sa_effectsize_cluster$label)
sa_effectsize_cluster$label <- gsub("rh_cdacate", "rh_caudalanteriorcingulate", sa_effectsize_cluster$label)
sa_effectsize_cluster$label <- gsub("rh_sufr", "rh_superiorfrontal", sa_effectsize_cluster$label)
sa_effectsize_cluster$label <- gsub("lh_sufr", "lh_superiorfrontal", sa_effectsize_cluster$label)
sa_effectsize_cluster$label <- gsub("rh_parsopc", "rh_parsopercularis", sa_effectsize_cluster$label)
sa_effectsize_cluster$label <- gsub("lh_ihcate", "lh_isthmuscingulate", sa_effectsize_cluster$label)
sa_effectsize_cluster$label <- gsub("lh_locc", "lh_lateraloccipital", sa_effectsize_cluster$label)
sa_effectsize_cluster$label <- gsub("rh_locc", "rh_lateraloccipital", sa_effectsize_cluster$label)
sa_effectsize_cluster$label <- gsub("lh_lobfr", "lh_lateralorbitofrontal", sa_effectsize_cluster$label)
sa_effectsize_cluster$label <- gsub("rh_lobfr", "rh_lateralorbitofrontal", sa_effectsize_cluster$label)
sa_effectsize_cluster$label <- gsub("lh_supl", "lh_superiorparietal", sa_effectsize_cluster$label)
sa_effectsize_cluster$label <- gsub("lh_supl", "lh_superiorparietal", sa_effectsize_cluster$label)
sa_effectsize_cluster$label <- gsub("lh_mobfr", "lh_medialorbitofrontal", sa_effectsize_cluster$label)
sa_effectsize_cluster$label <- gsub("rh_mobfr", "rh_medialorbitofrontal", sa_effectsize_cluster$label)
sa_effectsize_cluster$label <- gsub("rh_frpole", "rh_frontalpole", sa_effectsize_cluster$label)
sa_effectsize_cluster$label <- gsub("lh_frpole", "lh_frontalpole", sa_effectsize_cluster$label)
sa_effectsize_cluster$label <- gsub("rh_paracn", "rh_paracentral", sa_effectsize_cluster$label)
sa_effectsize_cluster$label <- gsub("lh_paracn", "lh_paracentral", sa_effectsize_cluster$label)
sa_effectsize_cluster$label <- gsub("lh_parsopc", "lh_parsopercularis", sa_effectsize_cluster$label)
sa_effectsize_cluster$label <- gsub("rh_parsopc", "rh_parsopercularis", sa_effectsize_cluster$label)
sa_effectsize_cluster$label <- gsub("rh_ihcate", "rh_isthmuscingulate", sa_effectsize_cluster$label)
sa_effectsize_cluster$label <- gsub("lh_parstgris", "lh_parstriangularis", sa_effectsize_cluster$label)
sa_effectsize_cluster$label <- gsub("lh_parsobis", "lh_parsorbitalis", sa_effectsize_cluster$label)
sa_effectsize_cluster$label <- gsub("rh_parsobis", "rh_parsorbitalis", sa_effectsize_cluster$label)
sa_effectsize_cluster$label <- gsub("lh_postcn", "lh_postcentral", sa_effectsize_cluster$label)
sa_effectsize_cluster$label <- gsub("rh_postcn", "rh_postcentral", sa_effectsize_cluster$label)
sa_effectsize_cluster$label <- gsub("lh_precn", "lh_precentral", sa_effectsize_cluster$label)
sa_effectsize_cluster$label <- gsub("rh_precn", "rh_precentral", sa_effectsize_cluster$label)
sa_effectsize_cluster$label <- gsub("lh_pc", "lh_precuneus", sa_effectsize_cluster$label)
sa_effectsize_cluster$label <- gsub("rh_pc", "rh_precuneus", sa_effectsize_cluster$label)
sa_effectsize_cluster$label <- gsub("rh_rrmdfr", "rh_rostralmiddlefrontal", sa_effectsize_cluster$label)
sa_effectsize_cluster$label <- gsub("lh_rrmdfr", "lh_rostralmiddlefrontal", sa_effectsize_cluster$label)
sa_effectsize_cluster$label <- gsub("lh_sutm", "lh_superiortemporal", sa_effectsize_cluster$label)
sa_effectsize_cluster$label <- gsub("rh_sutm", "rh_superiortemporal", sa_effectsize_cluster$label)
sa_effectsize_cluster$label <- gsub("rh_supl", "rh_superiorparietal", sa_effectsize_cluster$label)

#plot
ggseg( 
      .data = sa_effectsize_cluster, 
      colour = "black",
      mapping = aes(fill = tstat), 
      position = "stacked") +
  theme_void() +
  scale_fill_gradient2(low = "blue", mid = "white", high = "red", midpoint = 0,lim = c(-6,6))+
  labs(title = "Surface area NonPLE - Cluster 1", fill = "T-stat")
```

Resting State Cortical-Cortical
```{r}
#Modify input accordingly
split2_C1_RS_effectsize <- read_csv("../split2_C1_RS_effectsize.csv")

split2_C1_RS_effectsize$Feature_Renamed <- sapply(split2_C1_RS_effectsize$Feature, rename_feature)

split2_C1_RS_effectsize <- split2_C1_RS_effectsize %>%
  mutate(Connection_Type = case_when(
    grepl("_scs_", Feature) ~ "Cortical-Subcortical",
    grepl("_ngd_", Feature) ~ "Cortical-Cortical",
    TRUE ~ "Other"
  ))

#First, cortical-cortical network connections
split2_C1_RS_effectsize_cort <- split2_C1_RS_effectsize %>%
  dplyr::filter(Connection_Type == "Cortical-Cortical") %>%
  dplyr::select(Feature_Renamed,tstat)

# Split the feature into 'from' and 'to' regions
split2_C1_RS_effectsize_cort <- split2_C1_RS_effectsize_cort %>%
  mutate(
    from = sub(" to .*", "", Feature_Renamed),
    to = sub(".* to ", "", Feature_Renamed)
  )

# Pivot to wide format
wide_mat <- split2_C1_RS_effectsize_cort %>%
  dplyr::select(from, to, tstat) %>%
  tidyr::pivot_wider(names_from = to, values_from = tstat)

# Convert to matrix and assign rownames
mat <- as.matrix(wide_mat[,-1])
rownames(mat) <- wide_mat$from

# Mirror to make a symmetric matrix
mat[lower.tri(mat)] <- t(mat)[lower.tri(mat)]

# Convert matrix to long format
mat_long <- melt(mat, varnames = c("From", "To"), value.name = "tstat")

# Get number of regions (matrix should be square)
n_regions <- length(unique(mat_long$To))

# Build stepped diagonal as a path
step_path <- data.frame(
  y = rep(1:n_regions, each = 2)[-1],
  x = rep(1:n_regions, each = 2)[-length(rep(1:n_regions, each = 2))]
)

# Adjust for tile centering (geom_tile aligns to centers)
step_path <- step_path %>%
  mutate(x = x + 0.5, y = y - 0.5)

# Plot
ggplot(mat_long, aes(x = From, y = To, fill = tstat)) +
  geom_tile(color = "white") +
  scale_fill_gradient2(low = "blue", mid = "white", high = "red", midpoint = 0,
                       limits = c(-7, 7)) +
  labs(title = "T-stat Heatmap", x = "", y = "") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        axis.text = element_text(size = 10),
        panel.grid = element_blank()) +
  geom_path(data = step_path, aes(x = x, y = y), inherit.aes = FALSE,
            color = "black", linewidth = 1)
```
Resting State Sub-cortical-Cortical
```{r}
# Extract unique region-network mappings from ggsegGordon
split2_C1_RS_effectsize_scort <- split2_C1_RS_effectsize %>%
  dplyr::filter(Connection_Type == "Cortical-Subcortical") %>%
  dplyr::select(Feature_Renamed,tstat)
# Split the feature into 'from' and 'to' regions
split2_C1_RS_effectsize_scort <- split2_C1_RS_effectsize_scort %>%
  mutate(
    from = sub(" to .*", "", Feature_Renamed),
    to = sub(".* to ", "", Feature_Renamed)
  )

# Pivot to wide format
wide_mat <- split2_C1_RS_effectsize_scort %>%
  dplyr::select(from, to, tstat) %>%
  tidyr::pivot_wider(names_from = to, values_from = tstat)

# Convert to matrix and assign rownames
mat <- as.matrix(wide_mat[,-1])
rownames(mat) <- wide_mat$from

# Mirror to make a symmetric matrix
mat[lower.tri(mat)] <- t(mat)[lower.tri(mat)]


# Convert matrix to long format
mat_long <- melt(mat, varnames = c("From", "To"), value.name = "tstat")

# Plot
ggplot(mat_long, aes(x = From, y = To, fill = tstat)) +
  geom_tile(color = "white") +
  scale_fill_gradient2(low = "blue", mid = "white", high = "red", midpoint = 0, limits = c(-7,7)) +
  labs(title = "T-stat Heatmap", x = "", y = "") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        axis.text = element_text(size = 10),
        panel.grid = element_blank())
```
